/**
  ******************************************************************************
  * @file    pitch_reg.h
  * @author  Thomas Reisnecker
  * @brief   tbd.
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef PITCH_REG_H_INCLUDED
#define PITCH_REG_H_INCLUDED

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

#include "sdk_errors.h"

/* Exported types ------------------------------------------------------------*/
typedef int16_t q15_t;

typedef enum
{
    PRG_TYPE_15,
    PRG_TYPE_22,
    PRG_TYPE_30,
    PRG_TYPE_CNT,
    PRG_TYPE_NA = 0xFF
} prg_opticType_t;

typedef struct
{
    prg_opticType_t type;
    q15_t           offset;
} prg_optic_t;

/* Exported constants --------------------------------------------------------*/

/* Exported macros -----------------------------------------------------------*/

/* Exported functions ------------------------------------------------------- */
/** @brief function to retrieve the pitch compensated intensity values
 *
 * @param[in]     pitch   the current pitch angle ([0..1] -> [0..2pi])
 * @param[in]     pOptic  the installed optic of each channels
 * @param[in/out] pInt    the intensities of each channels
 * @return        NRF_SUCCESS, NRF_ERROR_NULL, NRF_ERROR_INVALID_PARAM
 */
ret_code_t prg_GetComp(q15_t pitch, prg_optic_t const* pOptic, int32_t* pInt);

/** @brief function to reduce the compensated values if different optics are used
 *
 * @note If you use 15° and 30° at the same time, you can use this function to
 *       reduce the intensities generated by prg_GetComp(). The intensity for
 *       15° optic will be linearly reduced between 0°..-22.5°. The intensity
 *       for the 30° optic will be reduced linearly between -22.5°..11.25°
 *
 * @param[in]     pitch   the current pitch angle ([0..1] -> [0..2pi])
 * @param[in]     pOptic  the installed optic of each channels
 * @param[in/out] pInt    the intensities of each channels
 * @return        NRF_SUCCESS, NRF_ERROR_NULL, NRF_ERROR_INVALID_PARAM
 */
ret_code_t prg_MultiOptic(q15_t pitch, prg_optic_t const* pOptic, int32_t* pInt);

#endif // PITCH_REG_H_INCLUDED

/**END OF FILE*****************************************************************/

